# Generated by Django 6.0.1 on 2026-01-21 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('simbolo', models.CharField(blank=True, default='', max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='bodega.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('POSTEADO', 'Posteado')], default='BORRADOR', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('observacion', models.TextField(blank=True, default='')),
                ('posteado_en', models.DateTimeField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, default='', max_length=120)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_movimientos', to='bodega.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('codigo_barra', models.CharField(blank=True, default='', max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('permite_fraccion', models.BooleanField(default=True)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=120)),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', to='bodega.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bodega.marca')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bodega.unidadmedida')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, default='', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('POSTEADO', 'Posteado')], default='BORRADOR', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('observacion', models.TextField(blank=True, default='')),
                ('posteado_en', models.DateTimeField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_movimientos', to='bodega.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='bodega.proveedor')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lote', models.CharField(blank=True, default='', max_length=80)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('movimiento_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='bodega.movimientoentrada')),
                ('movimiento_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='bodega.movimientosalida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_movimiento', to='bodega.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['producto'], name='bodega_movi_product_ed91aa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movimiento_entrada__isnull', False), ('movimiento_salida__isnull', True)), models.Q(('movimiento_entrada__isnull', True), ('movimiento_salida__isnull', False)), _connector='OR'), name='linea_xor_entrada_salida')],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_proveedor', models.CharField(blank=True, default='', max_length=80)),
                ('costo_ultima_compra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='bodega.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bodega.proveedor')),
            ],
            options={
                'ordering': ['-es_principal', 'proveedor__nombre'],
                'unique_together': {('producto', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bodega.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bodega.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['bodega', 'producto'], name='bodega_stoc_bodega__3ef6a6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='stock_no_negativo')],
                'unique_together': {('bodega', 'producto')},
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='bodega_prod_sku_8f42ef_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='bodega_prod_nombre_69450d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barra'], name='bodega_prod_codigo__430f4e_idx'),
        ),
    ]
